imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.users_images: /users/image
    app.path.users_pdf: /users/pdf
    app.path.universites_pdf: /universites/pdf
    app.path.demandes_pdf: /demandes/pdf

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        cookie_lifetime: 604800
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        admin_skin: skin-blue
        root_path: %kernel.root_dir%
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: false #'%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    auth_mode: '%mailer_auth_mode%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    spool: { type: memory }

# LexikFormFilter Configuration
lexik_form_filter:
    listeners:
        doctrine_orm: true
        doctrine_dbal: false
        doctrine_mongodb: false
lexik_form_filter:
    where_method: ~  # null | and | or
lexik_form_filter:
    condition_pattern: text.starts

# FOSUserBundle Configuration
fos_user:
    db_driver:              orm # Required
    firewall_name:          main # Required
    user_class:             DUDEEGO\PlatformBundle\Entity\User # Required
    use_listener:           true
    use_flash_notifications: true
    use_authentication_listener: true
    use_username_form_type: true
    model_manager_name:     null  # change it to the name of your entity/document manager if you don't want to use the default one.
    from_email:
        address:        "%mailer_user%"
        sender_name:    "%mailer_user%"
    profile:
        form:
            type:               FOS\UserBundle\Form\Type\ProfileFormType # or 'fos_user_profile' on Symfony < 2.8
            name:               fos_user_profile_form
            validation_groups:  [Profile, Default]
    change_password:
        form:
            type:               FOS\UserBundle\Form\Type\ChangePasswordFormType # or 'fos_user_change_password' on Symfony < 2.8
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword, Default]
    registration:
        confirmation:
            from_email: # Use this node only if you don't want the global email address for the confirmation email
                address:        "%mailer_user%"
                sender_name:    "%mailer_user%"
            enabled:    false # change to true for required email confirmation
            template:   '@FOSUser/Registration/email.txt.twig'
        form:
            type:               DUDEEGO\PlatformBundle\Form\RegistrationType # or 'fos_user_registration' on Symfony < 2.8
            name:               fos_user_registration_form
            validation_groups:  [Registration, Default]
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address:        "%mailer_user%"
                sender_name:    "%mailer_user%"
            template:   '@FOSUser/Resetting/email.txt.twig'
        form:
            type:               FOS\UserBundle\Form\Type\ResettingFormType # or 'fos_user_resetting' on Symfony < 2.8
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]
    service:
        mailer:                 fos_user.mailer.default
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default

# OneupFlysystemBundle Configuration
oneup_flysystem:
    adapters:
        users_adapter:
            local:
                directory: %kernel.root_dir%/../web/images/users
    filesystems:
        users_image_fs:
           adapter:    users_adapter
           mount:      users_image_fs

# VichUploaderBundle Configuration
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
#    storage:   flysystem
    mappings:
        users_images:
            namer:              vich_uploader.namer_origname
            uri_prefix:         '%app.path.users_images%'
            upload_destination: '%kernel.root_dir%/../web/users/image'            
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        users_pdf:
            namer:              vich_uploader.namer_origname
            uri_prefix:         '%app.path.users_pdf%'
            upload_destination: '%kernel.root_dir%/../web/users/pdf'            
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        universites_pdf:
            namer:              vich_uploader.namer_origname
            uri_prefix:         '%app.path.universites_pdf%'
            upload_destination: '%kernel.root_dir%/../web/universites/pdf'            
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        demandes_pdf:
            namer:              vich_uploader.namer_origname
            uri_prefix:         '%app.path.demandes_pdf%'
            upload_destination: '%kernel.root_dir%/../web/demandes/pdf'            
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

# FOSRestBundle Configuration 
#fos_rest:
#    format_listener:
#        enabled: true
#        rules:
            # ... previous rules declarations
#            - { path: '^/admin', stop: true }  # <-- add this line
# Easy Admin Configuration            
easy_admin:
    list:
        max_results: 30
        actions:
            - { name: 'show', icon: 'search', label: false }
            - { name: 'edit', icon: 'pencil', label: false  }
            - { name: 'delete', icon: 'trash', label: false }
    site_name: 'DUDEEGO PlatformAdmin.'
    design:
        form_theme: ['horizontal', 'VichUploaderBundle:Form:fields.html.twig']
        brand_color: 'blue' # any color or rgb
        color_scheme: 'light' #dark
        menu:
            - label: 'Gestion Universite'
              children: ['Universite', 'Image', 'Adresse', 'Ville', 'Pays', 'Formation', 'Langue', 'Documents']
            - label: 'Gestion Utilisateur'
              children: ['Adresse', 'Etudiant', 'Entreprise','Langue', 'Utilisateur', 'Image', 'Demandes_Inscriptions', 'Documents_Inscriptions', 'Documents_Utilisateur', 'FAQ']
    entities:
        Universite:
            class: DUDEEGO\PlatformBundle\Entity\T_Universite
            form:
                fields:
                    - { property: 'nometablissement' }
                    - { property: 'siteinternet' }
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'documents' }
                    - { property: 'formations' }
                    - { property: 'images' }
                    - { property: 'adresse' }
        Documents:
            class: DUDEEGO\PlatformBundle\Entity\T_Document_Universite
        Adresse:
            class: DUDEEGO\PlatformBundle\Entity\T_Adresse_Universite
        Ville:
            class: DUDEEGO\PlatformBundle\Entity\T_Ville_Universite
        Pays:
            class: DUDEEGO\PlatformBundle\Entity\T_Pays_Universite
        Formation:
            class: DUDEEGO\PlatformBundle\Entity\T_Formation_Universite
        Langue:
            class: DUDEEGO\PlatformBundle\Entity\T_Langue_Universite
        Image:
            class: DUDEEGO\PlatformBundle\Entity\T_Image_Universite
        Adresse:
            class: DUDEEGO\PlatformBundle\Entity\EA_Personne
        Etudiant:
            class: DUDEEGO\PlatformBundle\Entity\EA_Physique
        Entreprise:
            class: DUDEEGO\PlatformBundle\Entity\EA_Morale
        Langue:
            class: DUDEEGO\PlatformBundle\Entity\EA_Langue
        Utilisateur:
            class: DUDEEGO\PlatformBundle\Entity\User
        Image:
            class: DUDEEGO\PlatformBundle\Entity\EA_Image
            list:
                fields:
                    - { property: 'imageName', type: 'image', base_path: '%app.path.users_images%' }
            show:
                fields:
                    - { property: 'imageName', type: 'image', base_path: '%app.path.users_images%' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
        Demandes_Inscriptions:
            class: DUDEEGO\PlatformBundle\Entity\EA_Demande_Inscription
        Documents_Inscriptions:
            class: DUDEEGO\PlatformBundle\Entity\EA_Document_Inscription
        Documents_Utilisateur:
            class: DUDEEGO\PlatformBundle\Entity\EA_Document
            list:
                fields:
                    - { property: 'PasseportName', template: 'contract.html.twig', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'CarteIdentiteName', template: 'contract.html.twig', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'BulletinNoteName', template: 'contract.html.twig', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'BacName', template: 'contract.html.twig', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'CredentialName', template: 'contract.html.twig', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'LettreRecommendationName', template: 'contract.html.twig', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'LettreMotivationName', template: 'contract.html.twig', type: 'file', base_path: '%app.path.users_pdf%' }
            show:
                fields:
                    - { property: 'PasseportName', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'CarteIdentiteName', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'BulletinNoteName', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'BacName', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'CredentialName', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'LettreRecommendationName', type: 'file', base_path: '%app.path.users_pdf%' }
                    - { property: 'LettreMotivationName', type: 'file', base_path: '%app.path.users_pdf%' }
            form:
                fields:
                    - { property: 'PasseportFile', type: 'vich_file' }
                    - { property: 'CarteIdentiteFile', type: 'vich_file' }
                    - { property: 'BulletinNoteFile', type: 'vich_file' }
                    - { property: 'BacFile', type: 'vich_file' }
                    - { property: 'CredentialFile', type: 'vich_file' }
                    - { property: 'LettreRecommendationFile', type: 'vich_file' }
                    - { property: 'LettreMotivationFile', type: 'vich_file' }
        FAQ:
            class: DUDEEGO\PlatformBundle\Entity\EA_FAQ