# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username  #id: fos_user.user_provider.useremail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            form_login:
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
                csrf_token_generator : security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                require_previous_session: false
            logout:       true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds

    access_control:
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/login$, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/register, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/resetting, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN, ROLE_ADMIN] }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/back, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        