# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
services:
    app.form.registration:
        class: DUDEEGO\PlatformBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    #remplace acme_user par ...
    acme_user.password_resetting:
        class: DUDEEGO\PlatformBundle\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
    app.form.handler.registration:
        class: DUDEEGO\PlatformBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false

