dudeego_platform_home:
    path:      /
    defaults: { _controller: DUDEEGOPlatformBundle:Front:index }
dudeego_platform_accueil:
    path:      /Front/accueil
    defaults: { _controller: DUDEEGOPlatformBundle:Front:accueil }    
dudeego_platform_showComparateur:
    path:      /Front/comparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Front:showComparateur }
dudeego_platform_detailsComparateur:
    path:      /Front/detailscomparateur/{id}
    defaults: { _controller: DUDEEGOPlatformBundle:Front:detailsComparateur }
dudeego_platform_PanierComparateur:
    path:      /Front/comparateur/{id}
    defaults: { _controller: DUDEEGOPlatformBundle:Front:PanierComparateur }
dudeego_platform_comparerComparateur:
    path:      /Front/comparer
    defaults: { _controller: DUDEEGOPlatformBundle:Front:comparerComparateur }
dudeego_platform_filterComparateur:
    path:      /Front/filtercomparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Front:filterComparateur }
    methods: POST
dudeego_platform_itemsComparateur:
    path:      /Front/itemsComparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Front:itemsComparateur }
    methods: POST|GET
dudeego_platform_voirJob:
    path:      /Front/job
    defaults: { _controller: DUDEEGOPlatformBundle:Front:job }
dudeego_platform_voirStage:
    path:      /Front/stage
    defaults: { _controller: DUDEEGOPlatformBundle:Front:stage }
dudeego_platform_voirLogement:
    path:      /Front/Logement
    defaults: { _controller: DUDEEGOPlatformBundle:Front:Logement }
dudeego_platform_voirLangue:
    path:      /Front/langue
    defaults: { _controller: DUDEEGOPlatformBundle:Front:langue }
dudeego_platform_voirBlog:
    path:      /Front/blog
    defaults: { _controller: DUDEEGOPlatformBundle:Front:blog }
dudeego_platform_voirTest:
    path:      /Front/test
    defaults: { _controller: DUDEEGOPlatformBundle:Front:test }

dudeego_platform_abonne_monProfil:
    path:      /Back/monprofil/
    defaults: { _controller: DUDEEGOPlatformBundle:Back:monprofil }
dudeego_platform_abonne_mesParametres:
    path:      /Back/mesparametres
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mesparametres }

dudeego_platform_abonne_mesDemandes:
    path:      /Back/mesdemandes
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mesdemandes }
dudeego_platform_abonne_detailsDemandes:
    path:      /Back/detailsdemandes/{id}
    defaults: { _controller: DUDEEGOPlatformBundle:Back:detailsdemandes }
dudeego_platform_abonne_modifierDemandes:
    path:      /Back/modifierdemandes/{id}
    defaults: { _controller: DUDEEGOPlatformBundle:Back:modifierdemandes }
    methods: GET|POST

dudeego_platform_abonne_mesDocuments:
    path:      /Back/mesdocuments
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mesdocuments }
dudeego_platform_abonne_aide:
    path:      /Back/aide
    defaults: { _controller: DUDEEGOPlatformBundle:Back:aide } 
dudeego_platform_abonne_contact:
    path:      /Back/contact
    defaults: { _controller: DUDEEGOPlatformBundle:Back:contact }
    methods: POST|GET 

dudeego_platform_abonne_universiteStepsOne:
    path:      /Back/universiteOne
    defaults: { _controller: DUDEEGOPlatformBundle:Back:universiteOne } 
dudeego_platform_abonne_universiteStepsTwo:
    path:      /Back/universiteTwo
    defaults: { _controller: DUDEEGOPlatformBundle:Back:universiteTwo } 
dudeego_platform_abonne_universiteStepsThree:
    path:      /Back/universiteThree
    defaults: { _controller: DUDEEGOPlatformBundle:Back:universiteTwo } 

dudeego_platform_abonne_langueStepsOne:
    path:      /Back/langueOne
    defaults: { _controller: DUDEEGOPlatformBundle:Back:langueOne } 
dudeego_platform_abonne_langueStepsTwo:
    path:      /Back/langueTwo
    defaults: { _controller: DUDEEGOPlatformBundle:Back:langueTwo } 
dudeego_platform_abonne_langueStepsThree:
    path:      /Back/langueThree
    defaults: { _controller: DUDEEGOPlatformBundle:Back:langueTwo } 

dudeego_platform_abonne_logementStepsOne:
    path:      /Back/logementOne
    defaults: { _controller: DUDEEGOPlatformBundle:Back:logementOne }    
dudeego_platform_abonne_logementStepsTwo:
    path:      /Back/logementTwo
    defaults: { _controller: DUDEEGOPlatformBundle:Back:logementTwo } 
dudeego_platform_abonne_logementStepsThree:
    path:      /Back/logementThree
    defaults: { _controller: DUDEEGOPlatformBundle:Back:logementTwo } 

dudeego_platform_abonne_preparation:
    path:      /Back/preparation
    defaults: { _controller: DUDEEGOPlatformBundle:Back:preparation }    
dudeego_platform_abonne_mutuelle:
    path:      /Back/mutuelle
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mutuelle }       

dudeego_platform_admin_panel:
    path:      /Admin/adminPanel
    defaults: { _controller: DUDEEGOPlatformBundle:Admin:adminPanel }  
