dudeego_platform_home:
    path:      /
    defaults: { _controller: DUDEEGOPlatformBundle:Page:index }
dudeego_platform_testComparateur:
    path:      /Page/testcomparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Page:testcomparateur }
dudeego_platform_testFilterComparateur:
    path:      /Page/testcomparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Page:testFilter }
    requirements:
        _method: GET
dudeego_platform_filtreComparateur:
    path:      /Page/comparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Page:filtrecomparateur }
    requirements:
        _method: POST
dudeego_platform_voirComparateur:
    path:      /Page/comparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Page:comparateur }
dudeego_platform_voirJob:
    path:      /Page/job
    defaults: { _controller: DUDEEGOPlatformBundle:Page:job }
dudeego_platform_voirStage:
    path:      /Page/stage
    defaults: { _controller: DUDEEGOPlatformBundle:Page:stage }
dudeego_platform_voirLogement:
    path:      /Page/Logement
    defaults: { _controller: DUDEEGOPlatformBundle:Page:Logement }
dudeego_platform_voirLangue:
    path:      /Page/langue
    defaults: { _controller: DUDEEGOPlatformBundle:Page:langue }
dudeego_platform_voirBlog:
    path:      /Page/blog
    defaults: { _controller: DUDEEGOPlatformBundle:Page:blog }


dudeego_platform_abonne_monProfil:
    path:      /PageAbonne/monprofil
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:monprofil }
dudeego_platform_abonne_mesParametres:
    path:      /PageAbonne/mesparametres
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:mesparametres }
dudeego_platform_abonne_mesDemandes:
    path:      /PageAbonne/mesdemandes
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:mesdemandes }
dudeego_platform_abonne_mesDocuments:
    path:      /PageAbonne/mesdocuments
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:mesdocuments }
dudeego_platform_abonne_aide:
    path:      /PageAbonne/aide
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:aide } 
 
dudeego_platform_abonne_universite:
    path:      /PageAbonne/universite
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:universite } 
dudeego_platform_abonne_langue:
    path:      /PageAbonne/langue
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:langue } 
dudeego_platform_abonne_logement:
    path:      /PageAbonne/logement
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:logement }    
dudeego_platform_abonne_preparation:
    path:      /PageAbonne/preparation
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:preparation }    
dudeego_platform_abonne_mutuelle:
    path:      /PageAbonne/mutuelle
    defaults: { _controller: DUDEEGOPlatformBundle:PageAbonne:mutuelle }       