dudeego_platform_home:
    path:      /
    defaults: { _controller: DUDEEGOPlatformBundle:Front:index }
dudeego_platform_accueil:
    path:      /Front/accueil
    defaults: { _controller: DUDEEGOPlatformBundle:Front:accueil }    
dudeego_platform_showComparateur:
    path:      /Front/comparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Front:showComparateur }
dudeego_platform_detailsComparateur:
    path:      /Front/detailscomparateur/{id}
    defaults: { _controller: DUDEEGOPlatformBundle:Front:detailsComparateur }
dudeego_platform_PanierComparateur:
    path:      /Front/comparateur/{id}
    defaults: { _controller: DUDEEGOPlatformBundle:Front:PanierComparateur }
dudeego_platform_comparerComparateur:
    path:      /Front/comparer
    defaults: { _controller: DUDEEGOPlatformBundle:Front:comparerComparateur }
dudeego_platform_filterComparateur:
    path:      /Front/filtercomparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Front:filterComparateur }
    methods: POST
dudeego_platform_itemsComparateur:
    path:      /Front/itemsComparateur
    defaults: { _controller: DUDEEGOPlatformBundle:Front:itemsComparateur }
    methods: POST|GET
dudeego_platform_voirJob:
    path:      /Front/job
    defaults: { _controller: DUDEEGOPlatformBundle:Front:job }
dudeego_platform_voirStage:
    path:      /Front/stage
    defaults: { _controller: DUDEEGOPlatformBundle:Front:stage }
dudeego_platform_voirLogement:
    path:      /Front/Logement
    defaults: { _controller: DUDEEGOPlatformBundle:Front:Logement }
dudeego_platform_voirLangue:
    path:      /Front/langue
    defaults: { _controller: DUDEEGOPlatformBundle:Front:langue }
dudeego_platform_voirBlog:
    path:      /Front/blog
    defaults: { _controller: DUDEEGOPlatformBundle:Front:blog }
dudeego_platform_voirTest:
    path:      /Front/test
    defaults: { _controller: DUDEEGOPlatformBundle:Front:test }

dudeego_platform_abonne_monProfil:
    path:      /Back/monprofil/
    defaults: { _controller: DUDEEGOPlatformBundle:Back:monprofil }
dudeego_platform_abonne_mesParametres:
    path:      /Back/mesparametres
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mesparametres }
dudeego_platform_abonne_mesDemandes:
    path:      /Back/mesdemandes
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mesdemandes }
dudeego_platform_abonne_addDemandes:
    path:      /Back/mesdemandes
    defaults: { _controller: DUDEEGOPlatformBundle:Back:addDemandes }
dudeego_platform_abonne_mesDocuments:
    path:      /Back/mesdocuments
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mesdocuments }
dudeego_platform_abonne_aide:
    path:      /Back/aide
    defaults: { _controller: DUDEEGOPlatformBundle:Back:aide } 
dudeego_platform_abonne_contact:
    path:      /Back/contact
    defaults: { _controller: DUDEEGOPlatformBundle:Back:contact }
    methods: POST|GET 
dudeego_platform_abonne_universite:
    path:      /Back/universite
    defaults: { _controller: DUDEEGOPlatformBundle:Back:universite } 
dudeego_platform_abonne_langue:
    path:      /Back/langue
    defaults: { _controller: DUDEEGOPlatformBundle:Back:langue } 
dudeego_platform_abonne_logement:
    path:      /Back/logement
    defaults: { _controller: DUDEEGOPlatformBundle:Back:logement }    
dudeego_platform_abonne_preparation:
    path:      /Back/preparation
    defaults: { _controller: DUDEEGOPlatformBundle:Back:preparation }    
dudeego_platform_abonne_mutuelle:
    path:      /Back/mutuelle
    defaults: { _controller: DUDEEGOPlatformBundle:Back:mutuelle }       

dudeego_platform_admin_panel:
    path:      /Admin/adminPanel
    defaults: { _controller: DUDEEGOPlatformBundle:Admin:adminPanel }  
