<?php

namespace Proxies\__CG__\DUDEEGO\PlatformBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class T_Formation_Universite extends \DUDEEGO\PlatformBundle\Entity\T_Formation_Universite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'langues', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'universite', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'id', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'formation', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'niveau', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'duree', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'requis', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'prix', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'salaire', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'tauxembauche', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'tauxreussite', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'concours'];
        }

        return ['__isInitialized__', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'langues', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'universite', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'id', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'formation', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'niveau', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'duree', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'requis', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'prix', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'salaire', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'tauxembauche', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'tauxreussite', '' . "\0" . 'DUDEEGO\\PlatformBundle\\Entity\\T_Formation_Universite' . "\0" . 'concours'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (T_Formation_Universite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormation($formation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormation', [$formation]);

        return parent::setFormation($formation);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormation', []);

        return parent::getFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function addLangue(\DUDEEGO\PlatformBundle\Entity\T_Langue_Universite $langue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLangue', [$langue]);

        return parent::addLangue($langue);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLangue(\DUDEEGO\PlatformBundle\Entity\T_Langue_Universite $langue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLangue', [$langue]);

        return parent::removeLangue($langue);
    }

    /**
     * {@inheritDoc}
     */
    public function getLangues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangues', []);

        return parent::getLangues();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniversite(\DUDEEGO\PlatformBundle\Entity\T_Universite $universite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniversite', [$universite]);

        return parent::setUniversite($universite);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniversite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniversite', []);

        return parent::getUniversite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$duree]);

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequis($requis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequis', [$requis]);

        return parent::setRequis($requis);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequis', []);

        return parent::getRequis();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalaire($salaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalaire', [$salaire]);

        return parent::setSalaire($salaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaire', []);

        return parent::getSalaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxembauche($tauxembauche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxembauche', [$tauxembauche]);

        return parent::setTauxembauche($tauxembauche);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxembauche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxembauche', []);

        return parent::getTauxembauche();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxreussite($tauxreussite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxreussite', [$tauxreussite]);

        return parent::setTauxreussite($tauxreussite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxreussite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxreussite', []);

        return parent::getTauxreussite();
    }

    /**
     * {@inheritDoc}
     */
    public function setConcours($concours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConcours', [$concours]);

        return parent::setConcours($concours);
    }

    /**
     * {@inheritDoc}
     */
    public function getConcours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConcours', []);

        return parent::getConcours();
    }

    /**
     * {@inheritDoc}
     */
    public function addUniversite(\DUDEEGO\PlatformBundle\Entity\T_Universite $universite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUniversite', [$universite]);

        return parent::addUniversite($universite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUniversite(\DUDEEGO\PlatformBundle\Entity\T_Universite $universite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUniversite', [$universite]);

        return parent::removeUniversite($universite);
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau($niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

}
