<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * EA_Demande_InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_Demande_InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
