<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * EA_LangueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_LangueRepository extends \Doctrine\ORM\EntityRepository
{
}
