<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * EA_PhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_PhysiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
