<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * F_Form_PreparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class F_Form_PreparationRepository extends \Doctrine\ORM\EntityRepository
{
}
