<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * T_Document_Admission8Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Document_Admission8Repository extends \Doctrine\ORM\EntityRepository
{
}
