<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * T_Formation_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Formation_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFormation($idEtablissement) {

		$qb = $this
		->createQueryBuilder('u')
		->where('u.id = :idEtablissement')
		->setParameter('idEtablissement', $idEtablissement)
		->orderBy('u.formation', 'ASC')
		;

		return $qb;
	}

		public function  getUniversiteCriteria($formations,  $langues) {
		
		$qb = $this
		->createQueryBuilder('u')
		->leftJoin('u.langues', 'lan')
		->where('u.id = :formations')
		->setParameter('formations', $formations)
		->andwhere('lan.id = :langues')
		->setParameter('langues', $langues)
		;

		return $qb;

	}
}
