<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * T_Image_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Image_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUniversiteWithImages()
	{
		$qb = $this
		->createQueryBuilder('a')
		->leftJoin('a.universite', 'univ')
		->addSelect('univ')
		;

		return $qb
		->getQuery()
		->getResult()
		;
	}
}
