<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * T_Langue_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Langue_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
}
