<?php

namespace DUDEEGO\PlatformBundle\Repository;

/**
 * T_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUniversiteWithSearch()
	{
		$qb = $this
		->createQueryBuilder('u')
		->leftJoin('u.formations', 'for')
		->addSelect('for')
		->leftJoin('u.images', 'ima')
		->addSelect('ima')
		->leftJoin('u.adresse', 'adr')
		->addSelect('adr')
		;

		return $qb
		->getQuery()
		->getResult()
		;
	}
}